version: "3.9"

services:

  db:
    image: mysql:9.6
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: habitos
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flask_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:123456@db:3306/habitos
      FLASK_APP: app.py
      FLASK_ENV: development

  solr:
    build: ./solr
    container_name: solr_server
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr/data


volumes:
  mysql_data:
  solr_data:
